### ISSUE TITLE
Add keyword not just domains 

### ISSUE THREAD

**Issue by charlieporth1** [maldevel/EmailHarvester#35]
Add keyword not just domains

**Comment by gcorrel** [comment]
I keep getting this error message everytime I tried extracting email leads from a domain name: "File "EmailHarvester.py", line 307, in <module>print(red("[-] Error saving TXT file: " + e))"

It refuses saving email addresses to the filename I specified plus it never real searches out lots of email addresses.

Again, are you implying searching with just a keyword, keywords instead of domain names? And if so, what switch should one use to specify keyword searches?

Thanks.

**Comment by gcorrel** [comment]
These are the complete error messages I get actually...

Traceback (most recent call last):
  File "EmailHarvester.py", line 312, in <module>
    print(red("[-] Error saving TXT file: " + e))
TypeError: cannot concatenate 'str' and 'exceptions.IOError' objects

**Comment by gcorrel** [comment]
Yeah, I edited my EmailHarvester.py file as you guys have specified right here and it's now working fine and saving list to file but if someone could be kind enough to show or direct me on how to perform searches with "keywords", I'd very much appreciate.

Thanks for your amazing works guys...lol

Cheers!!

**Comment by gcorrel** [comment]
Yeah, I edited my EmailHarvester.py file as you guys have specified right here and it's now working fine and saving list to file but if someone could be kind enough to show or direct me on how to perform searches with "keywords", I'd very much appreciate.

Thanks for your amazing works guys...lol

Cheers!!

**Comment by gcorrel** [comment]
Hello, is nobody reading through or monitoring this page anymore?

**Comment by charlieporth1** [comment]
No sorry I am github doesn't give me notifications

**Comment by JorgeDDW** [comment]
how to perform searches with "keywords"?

**Comment by ishandutta2007** [comment]
Original repo doesn't seem to be maintained any more nor are they accepting pull requests.
I am supporting Keyword on my fork. https://github.com/ishandutta2007/EmailHarvester

**Comment by maldevel** [comment]
Yes. I would like to add the keywords search capability. Please also check this project: https://github.com/twelvesec/gasmask
