### ISSUE TITLE
ImportError: No module named 'termcolor'

### ISSUE THREAD

**Issue by mathiasleroy** [maldevel/EmailHarvester#9]
It says "ImportError: No module named 'termcolor'"  
While it said just before "Successfully installed termcolor"

	:~/workspace/EmailHarvester (master) $ sudo pip install -r requirements.txt --user
	Requirement already satisfied (use --upgrade to upgrade): termcolor in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 1))
	Requirement already satisfied (use --upgrade to upgrade): colorama in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 2))
	Requirement already satisfied (use --upgrade to upgrade): requests in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 3))
	Cleaning up...
	
	:~/workspace/EmailHarvester (master) $ ./EmailHarvester.py -d teslamotors.com -e all
	Traceback (most recent call last):
	  File "./EmailHarvester.py", line 42, in <module>
	    from termcolor import colored
	ImportError: No module named 'termcolor'

	:~/workspace/EmailHarvester (master) $ pip install -r requirements.txt --user
	Requirement already satisfied (use --upgrade to upgrade): termcolor in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 1))
	Requirement already satisfied (use --upgrade to upgrade): colorama in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 2))
	Requirement already satisfied (use --upgrade to upgrade): requests in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 3))
	Cleaning up...
	
	:~/workspace/EmailHarvester (master) $ ./EmailHarvester.py -d teslamotors.com -e all
	Traceback (most recent call last):
	  File "./EmailHarvester.py", line 42, in <module>
	    from termcolor import colored
	ImportError: No module named 'termcolor'

**Comment by liar666** [comment]
I had the same problem... Had multiple python installed: 2.7 3.4 & 3.5.

Forcing use of 2.7 did the trick here...(either by running "python2.7 EmailHarvester.py ..." or changing EmailHarvester shebang with "#!/usr/bin/env python2.7")

**Comment by maldevel** [comment]
you have to use python 3.x and also install the requirements for python 3.x not 2.7

**Comment by mathiasleroy** [comment]
How do you "install the requirements for python 3.x not 2.7"?

**Comment by liar666** [comment]
That's probably a very basic info for python devs, but I would be interested in the answer too, as following the README's instructions (https://github.com/maldevel/EmailHarvester#downloadinstallation) led me to a wrong install. I tried using pip2, but with no more luck.
BTW I'm using python2.7 and everything works fine :)

**Comment by mathiasleroy** [comment]
I tried using python 2.7 like you suggested but it's not working

EmailHarvester.py -d example.com -e all                                                                                                                       
	./EmailHarvester.py: line 27: 
	    This file is part of EmailHarvester
	    Copyright (C) 2016 @maldevel
	    https://github.com/maldevel/EmailHarvester
	    
	    EmailHarvester - A tool to retrieve Domain email addresses from Search Engines.

	    This program is free software: you can redistribute it and/or modify
	    it under the terms of the GNU General Public License as published by
	    the Free Software Foundation, either version 3 of the License, or
	    (at your option) any later version.

	    This program is distributed in the hope that it will be useful,
	    but WITHOUT ANY WARRANTY; without even the implied warranty of
	    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	    GNU General Public License for more details.

	    You should have received a copy of the GNU General Public License
	    along with this program.  If not, see <http://www.gnu.org/licenses/>.
	    
	    For more see the file 'LICENSE' for copying permission.
	: No such file or directory
	./EmailHarvester.py: line 29: __author__: command not found
	./EmailHarvester.py: line 30: __copyright__: command not found
	./EmailHarvester.py: line 31: __credits__: command not found
	./EmailHarvester.py: line 32: __license__: command not found
	./EmailHarvester.py: line 33: __version__: command not found
	./EmailHarvester.py: line 34: __maintainer__: command not found
	./EmailHarvester.py: line 37: import: command not found
	./EmailHarvester.py: line 38: import: command not found
	./EmailHarvester.py: line 39: import: command not found
	./EmailHarvester.py: line 40: import: command not found
	./EmailHarvester.py: line 41: import: command not found
	./EmailHarvester.py: line 42: import: command not found
	from: can't read /var/mail/termcolor
	from: can't read /var/mail/argparse
	from: can't read /var/mail/sys
	from: can't read /var/mail/urllib.parse
	./EmailHarvester.py: line 54: syntax error near unexpected token `class'
	./EmailHarve

**Comment by liar666** [comment]
OK. Sorry for the wrong indication... I use Ubuntu with 3 versions of Python... Probably something is messed up in this installation and using explicitly python2.7 uses in fact (some parts of) python3x...

**Comment by mathiasleroy** [comment]
found the solution

    pip3 install -r requirements.txt --user

**Comment by Roslekas** [comment]
1. manualy need to create folder /root/.local/lib/python3.4/site-packages
2. copy site-packages from /root/.local/lib/python2.7/site-packages to /usr/local/lib/python3.4
3. pip install --upgrade --target=/root/.local/lib/python3.4/site-packages colorama
4. pip install --upgrade --target=/root/.local/lib/python3.4/site-packages tempcolor
5. pip install --upgrade --target=/root/.local/lib/python3.4/site-packages requests

for me helped

**Comment by xprotector** [comment]
### **sudo apt-get install python-pip
sudo pip install termcolor**

**Comment by NoName1488** [comment]
> sudo apt-get install python-pip
> sudo pip install termcolor

Thanks!

**Comment by zwein94** [comment]
problem has been solved with me after **### uninstall all python versions**

**Comment by AjarnSpencer** [comment]
First check if Python is globally installed and root is set properly, otherwise install python  in the EmailHarvester folder extra, or, uninstall python where you placed it and re-install it globally. Always best to create a virtual environment in your work folder or root home too to ensure more sure results.

### Ubuntu/Linux non Kali;
You don't need to open the terminal in any specific folder to install termcolor.

The pip3 install termcolor command will install the termcolor package globally on your system, making it available for use in any Python script or project.

Here's a breakdown of the steps:

Open your terminal: This can be done from your start menu or by using a keyboard shortcut (like Ctrl+Alt+T on most Linux systems).
Run the command: `Type pip3 install termcolor `
and press Enter.

That's it! The termcolor package will be installed, and you can use it in your Python scripts without any further setup.

 use python3 -m pip install termcolor to explicitly specify that you want to install the termcolor package for Python 3.

The reason for this is that some systems might have both Python 2 and Python 3 installed, and using pip alone could potentially install the package for the wrong version.

By using python3 -m pip install termcolor, you ensure that the package is installed for the correct Python version.


##However you may get this warning;
`.rvm/scripts/rvm: No such file or director.
`
Understanding the Error: bash: /home/cicada/.rvm/scripts/rvm: No such file or directory
This error indicates that RVM (Ruby Version Manager) is not installed or correctly configured on your system.

**What is RVM?**
RVM is a command-line tool that allows you to manage multiple Ruby environments on a single machine.

**Resolving the Issue:**
1. Check RVM Installation:

**Open your terminal and run:**

`type rvm`

If RVM is installed, it will show something like rvm is a function.
If it doesn't, proceed to step 2.
2. Install RVM:

Follow the official RVM installation instructions: https://rvm.io/rvm/install
Make sure to follow the instructions carefully, including adding the necessary lines to your .bashrc or .zshrc file.

`Source .bashrc or .zshrc:`

After installing RVM, you need to source your shell configuration file:

`source ~/.bashrc`

or
`source ~/.zshrc`

This will (or should if dependencies are all present), load the RVM environment variables into your current shell session.

**4. Verify RVM Installation:**

Try running rvm --version again. If it shows the RVM version, the installation was successful.
Additional Tips:
RVM Documentation: Refer to the official RVM documentation for detailed instructions and troubleshooting: 

**Specific Issues:** If you encounter any specific problems during the installation or usage of RVM, provide more details about the error messages or unexpected behavior.

RVM is not installed on your system.

**Installing RVM**
1. Open your terminal.
2. Paste the following command and press Enter:


`\curl -sSL https://get.rvm.io | bash -s stable`

###Source your shell configuration:

**For Bash:**

`source ~/.bashrc`

**For Zsh:**

source ~/.zshrc

**Verify the installation:**

rvm --version

f you encounter issues during the installation, refer to the official RVM documentation for detailed troubleshooting: https://rvm.io/rvm/install
You might need to open a new terminal session after sourcing your shell configuration for the changes to take effect.

If you see this

```
> RVM Installation Error: GPG Signature Verification Failed
> The RVM installation encountered an error during the download process. It's unable to verify the downloaded file's signature using GPG (GNU Privacy Guard) because the necessary public key is missing.
```

**_Here's how to fix this and complete the installation:_**

**1. Install GPG:**

You don't have GPG installed, or it's not configured correctly.
Open your terminal and run the following command (specific to your system):

**Ubuntu/Debian:**
```
sudo apt update
sudo apt install gnupg
```

**CentOS/RHEL/Fedora:**


`sudo yum install gnupg`


**2. Import Public Keys:**

The downloaded file requires specific public keys for verification.

**Run the following commands in your terminal:**


```
gpg --keyserver hkp://keyserver.ubuntu.com --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
Use code [with caution.](https://github.com/faq#coding)
```

If the previous command fails, use these alternatives:   

```
curl -sSL https://rvm.io/mpapis.asc | gpg --import -
curl -sSL https://rvm.io/pkuczynski.asc | gpg --import -

```

**3. Re-attempt Installation:**

Now that GPG is installed and the public keys are imported, re-run the installation command:

`\curl -sSL https://get.rvm.io | bash -s stable`


**4. Source Shell Configuration (Optional):**

The error message regarding source ~/.bashrc might be a leftover message.

If the installation completes successfully, you can try sourcing your shell configuration again:

`source ~/.bashrc`


**5. Verify RVM:**

If the installation finishes without errors, try running:

`rvm --version`


This should display the installed RVM version.

**Additional Notes:**

If you encounter further issues, refer to the RVM documentation on security for troubleshooting: 

[RVM Security page](https://rvm.io/rvm/security)

By following  this mass of sequential actions to make yourself crazy,  you should be able to successfully install RVM on your system.

Hope you see this soon!;
```
 _____                   _  _   _   _                                _
|
  ___|                 (_)| | | | | |                              | |
| |__  _ __ ___    __ _  _ | | | |_| |  __ _  _ __ __   __ ___  ___ | |_  ___  _ __
|  __|| '_ ` _ \  / _` || || | |  _  | / _` || '__|\ \ / // _ \/ __|| __|/ _ \| '__|
| |___| | | | | || (_| || || | | | | || (_| || |    \ V /|  __/\__ \| |_|  __/| |
\____/|_| |_| |_| \__,_||_||_| \_| |_/ \__,_||_|     \_/  \___||___/ \__|\___||_|
   A tool to retrieve Domain email addresses from Search Engines | @maldevel
                                Version: 1.3.2

optional arguments:
  -h, --help            show this help message and exit
  -d DOMAIN, --domain DOMAIN
                        Domain to search.
  -s FILE, --save FILE  Save the results into a TXT and XML file (both).
  -e ENGINE, --engine ENGINE
                        Select search engine(google, bing, yahoo, ask, all).
  -l LIMIT, --limit LIMIT
                        Limit the number of results.
  -u USER-AGENT, --user-agent USER-AGENT
                        Set the User-Agent request header.
  -x PROXY, --proxy PROXY
                        Setup proxy server (example: http://127.0.0.1:8080)
  --noprint             EmailHarvester will print discovered emails to terminal. 
						It is possible to tell EmailHarvester not to print results to terminal with this option.
  -r EXCLUDED_PLUGINS, --exclude EXCLUDED_PLUGINS
                        Plugins to exclude when you choose 'all' for search engine (eg. '-r google,twitter'
)
  -p, --list-plugins    List all available plugins.
```
